import GBA_USBC from './GB-Front-Front_USBC-02.webp';
import GBA_BUTTON_BLACK from './GB-Front-GB_FRONT_BUTTON_Black0023.webp';
import GBA_BUTTON_BLUE from './GB-Front-GB_FRONT_BUTTON_Black0023.webp';
import GBA_BUTTON_CLEARBLACK from './GB-Front-GB_FRONT_BUTTON_Blue0023.webp';
import GBA_BUTTON_CLEARBLUE from './GB-Front-GB_FRONT_BUTTON_ClearBlack0023.webp';
import GBA_BUTTON_CLEARGRASS from './GB-Front-GB_FRONT_BUTTON_ClearGlass0023.webp';
import GBA_BUTTON_CLEARGREEN from './GB-Front-GB_FRONT_BUTTON_ClearGreen0023.webp';
import GBA_BUTTON_CLEARORANGE from './GB-Front-GB_FRONT_BUTTON_ClearOrange0023.webp';
import GBA_BUTTON_DMG from './GB-Front-GB_FRONT_BUTTON_DMG0023.webp';
import GBA_BUTTON_GREY from './GB-Front-GB_FRONT_BUTTON_Grey0023.webp';
import GBA_BUTTON_ORANGE from './GB-Front-GB_FRONT_BUTTON_Orange0023.webp';
import GBA_BUTTON_RED from './GB-Front-GB_FRONT_BUTTON_Red0023.webp';
import GBA_BUTTON_ROSE from './GB-Front-GB_FRONT_BUTTON_Rose0023.webp';
import GBA_BUTTON_WHITE from './GB-Front-GB_FRONT_BUTTON_White0023.webp';
import GBA_IPS_BLACK from './GB-Front-GB_FRONT_IPS_BLACK.webp';
import GBA_IPS_DMG from './GB-Front-GB_FRONT_IPS_DMG.webp';
import GBA_PAD_BLACK from './GB-Front-GB_FRONT_PAD_Black0023.webp';
import GBA_PAD_BLUE from './GB-Front-GB_FRONT_PAD_Blue0023.webp';
import GBA_PAD_CLEAR from './GB-Front-GB_FRONT_PAD_Clear0023.webp';
import GBA_PAD_GREEN from './GB-Front-GB_FRONT_PAD_Green0023.webp';
import GBA_PAD_RED from './GB-Front-GB_FRONT_PAD_Red0023.webp';
import GBA_PAD_ROSE from './GB-Front-GB_FRONT_PAD_Rose0023.webp';
import GBA_PAD_VIOLET from './GB-Front-GB_FRONT_PAD_Violet0023.webp';
import GBA_PAD_YELLOW from './GB-Front-GB_FRONT_PAD_Yellow0023.webp';
import GBA_SHELL_BLACK from './GB-Front-GB-GB_FRONT_SHELL_Black0023.webp';
import GBA_SHELL_BLUE from './GB-Front-GB-GB_FRONT_SHELL_Blue0023.webp';
import GBA_SHELL_CLEARBLACK from './GB-Front-GB-GB_FRONT_SHELL_ClearBlack0023.webp';
import GBA_SHELL_CLEARBLUE from './GB-Front-GB-GB_FRONT_SHELL_ClearBlue0023.webp';
import GBA_SHELL_CLEARBLUEOCEAN from './GB-Front-GB-GB_FRONT_SHELL_ClearBlueOcean0023.webp';
import GBA_SHELL_CLEARGLASS from './GB-Front-GB-GB_FRONT_SHELL_ClearGlass0023.webp';
import GBA_SHELL_CLEARORANGE from './GB-Front-GB-GB_FRONT_SHELL_ClearOrange0023.webp';
import GBA_SHELL_CLEARRED from './GB-Front-GB-GB_FRONT_SHELL_ClearRed0023.webp';
import GBA_SHELL_DMG from './GB-Front-GB-GB_FRONT_SHELL_DMG0023.webp';
import GBA_SHELL_GHOST from './GB-Front-GB-GB_FRONT_SHELL_Ghost0023.webp';
import GBA_SHELL_GREEN from './GB-Front-GB-GB_FRONT_SHELL_Green0023.webp';
import GBA_SHELL_RED from './GB-Front-GB-GB_FRONT_SHELL_Red0023.webp';
import GBA_SHELL_WHITE from './GB-Front-GB-GB_FRONT_SHELL_White0023.webp';
import GBA_SHELL_YELLOW from './GB-Front-GB-GB_FRONT_SHELL_Yellow0023.webp';

export {
  GBA_USBC,
  GBA_BUTTON_BLACK,
  GBA_BUTTON_BLUE,
  GBA_BUTTON_CLEARBLACK,
  GBA_BUTTON_CLEARBLUE,
  GBA_BUTTON_CLEARGRASS,
  GBA_BUTTON_CLEARGREEN,
  GBA_BUTTON_CLEARORANGE,
  GBA_BUTTON_DMG,
  GBA_BUTTON_GREY,
  GBA_BUTTON_ORANGE,
  GBA_BUTTON_RED,
  GBA_BUTTON_ROSE,
  GBA_BUTTON_WHITE,
  GBA_IPS_BLACK,
  GBA_IPS_DMG,
  GBA_PAD_BLACK,
  GBA_PAD_BLUE,
  GBA_PAD_CLEAR,
  GBA_PAD_GREEN,
  GBA_PAD_RED,
  GBA_PAD_ROSE,
  GBA_PAD_VIOLET,
  GBA_PAD_YELLOW,
  GBA_SHELL_BLACK,
  GBA_SHELL_BLUE,
  GBA_SHELL_CLEARBLACK,
  GBA_SHELL_CLEARBLUE,
  GBA_SHELL_CLEARBLUEOCEAN,
  GBA_SHELL_CLEARGLASS,
  GBA_SHELL_CLEARORANGE,
  GBA_SHELL_CLEARRED,
  GBA_SHELL_DMG,
  GBA_SHELL_GHOST,
  GBA_SHELL_GREEN,
  GBA_SHELL_RED,
  GBA_SHELL_WHITE,
  GBA_SHELL_YELLOW,
};
